### ISSUE TITLE
Shared connection pool

### ISSUE THREAD

**Issue by ghost** [stanislav-az/news-rest-rs#9]
Each endpoint handler establishes a connection

https://github.com/stanislav-az/news-rest-rs/blob/5ca65338b65bd2b9fe225a422979134f892efd02/src/news/handlers/users.rs#L53

A preffered way would be to share a connection pool, like so:
```rust
use diesel_async::pooled_connection::AsyncDieselConnectionManager;
use diesel_async::pooled_connection::deadpool::Pool as DieselPool;
use diesel_async::AsyncPgConnection;

pub fn build_pool(url: &str) -> DieselPool<AsyncPgConnection> {
  let mgr = AsyncDieselConnectionManager::<AsyncPgConnection>::new(url);
  DieselPool::builder(mgr).build().unwrap()
}

pub type Pool = DieselPool<AsyncPgConnection>;
```

and when creating a router:
```rust
let pool = build_pool(&db_url);
axum::Router::new()
  .axum::routing::get(|axum::extract::State(env): axum::extract::State<env>| {
     let mut conn = self.db_pool.get().await?;
     ...
  })
  .with_state(Env{db_pool: pool})
```

**Comment by stanislav-az** [comment]
Hey @vladwix connection pool added. I do not use `diesel-async` though, do you think this is a good idea to transition from `diesel` to `diesel-async` ? Personally, I think for small handlers, which are doing one or two things with db, it is redundant.
